# Generated by Django 6.0.7 on 2026-07-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('project_brief', models.TextField()),
                ('sent', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='portfoliovideo',
            name='category',
            field=models.CharField(choices=[('youtube', 'Youtube'), ('short_reels', 'Shorts / Reels'), ('dtc_ugc', 'DTC / UGC'), ('ads', 'Ads'), ('live_action', 'Live Action'), ('motion_design', 'Motion Design'), ('movies', 'Movies')], max_length=100),
        ),
    ]
