# Generated by Django 6.0.7 on 2026-08-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_portfoliovideo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliovideo',
            name='category',
            field=models.CharField(choices=[('youtube', 'Youtube'), ('short_reels', 'Shorts / Reels'), ('dtc_ugc', 'DTC / UGC'), ('ads', 'Ads'), ('live_action', 'Live Action'), ('motion_design', 'Motion Design'), ('movies', 'Movies'), ('coporate', 'Coporate'), ('reel', 'Reel')], max_length=100),
        ),
    ]
