# Generated by Django 6.0.7 on 2026-08-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_portfoliovideo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliovideo',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
