# Generated by Django 6.0.7 on 2026-09-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_portfoliovideo_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliovideo',
            name='category',
            field=models.CharField(choices=[('youtube', 'Youtube'), ('short_reels', 'Shorts / Reels'), ('dtc_ugc', 'DTC / UGC'), ('ads', 'Ads'), ('live_action', 'Live Action'), ('motion_design', 'Motion Design'), ('movies', 'Movies'), ('corporate', 'Corporate'), ('reel', 'Reel'), ('ai_videos', 'AI Videos')], max_length=100),
        ),
    ]
